# -*- coding: utf-8 -*-
"""Bike Analysis - Bangkit

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p3a2AXQDAkVmAyFho2oNFSFuCrjyikqq

# Proyek Analisis Data: [Input Nama Dataset]
- **Nama:** Dyan Aqlima Febriyanti
- **Email:** dyanaqlima323@gmail.com
- **ID Dicoding:** dyanaqlima

## Menentukan Pertanyaan Bisnis
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
st.set_option('deprecation.showPyplotGlobalUse', False)
sns.set(style='dark')

day_df=pd.read_csv('https://raw.githubusercontent.com/dyanaqlima323/Machine-Learning-Bangkit-H1/8a153b8c0b68ee947840c89c75c4ca6f581c6d21/day.csv')

hour_df=pd.read_csv('https://raw.githubusercontent.com/dyanaqlima323/Machine-Learning-Bangkit-H1/8a153b8c0b68ee947840c89c75c4ca6f581c6d21/hour.csv')


#Mengganti tipe data
hour_df['dteday'] = pd.to_datetime(hour_df['dteday'])

#Mengubah nama kolom
hour_df.rename(columns={'dteday' : 'date', 'yr': 'year', 'mnth': 'month', 'hr' : 'hour'}, inplace=True)


# Judul Dashboard
st.title("🚲Bike Sharing Dashboard🚲")

# Pisahkan data berdasarkan hari libur dan non-libur
holiday_data = day_df[day_df['holiday'] == 1]
non_holiday_data = day_df[day_df['holiday'] == 0]

# Hitung rata-rata jumlah pengguna sepeda untuk setiap kategori
avg_cnt_holiday = holiday_data['cnt'].mean()
avg_cnt_non_holiday = non_holiday_data['cnt'].mean()

# Tampilkan rata-rata jumlah pengguna sepeda pada hari libur dan non-libur
st.subheader('Average Bike Users on Holiday vs. Non-Holiday')
col1, col2 = st.columns(2)

with col1:
    st.metric("Holiday", value=avg_cnt_holiday)

with col2:
    st.metric("Non-Holiday", value=avg_cnt_non_holiday)

# Visualisasikan perbedaan jumlah pengguna sepeda antara hari libur dan non-libur
plt.figure(figsize=(6, 4))
plt.bar(['Holiday', 'Non-Holiday'], [avg_cnt_holiday, avg_cnt_non_holiday], color=['red', '#28E841'])
plt.title('Average Bike Users on Holiday vs. Non-Holiday')
plt.xlabel('Day Type')
plt.ylabel('Average Bike Users (cnt)')
st.pyplot()


# Buat strip plot untuk membandingkan jumlah pengguna sepeda berdasarkan kondisi cuaca
st.subheader('Effect of Weather Conditions on Bike Usage')

plt.figure(figsize=(8, 6))
sns.stripplot(x='weathersit', y='cnt', data=day_df, palette=['purple', 'pink', 'blue'], alpha=0.7)
plt.title('Effect of Weather Conditions on Bike Usage')
plt.xlabel('Weather Condition')
plt.ylabel('Bike Users Count')
plt.xticks(ticks=[0, 1, 2], labels=['Clear', 'Mist', 'Light Rain/Heavy Rain'])
plt.grid(True)
st.pyplot()




# Tampilan Streamlit
st.sidebar.markdown("[Download Dataset](https://www.kaggle.com/code/ramanchandra/bike-sharing-data-analysis)")

st.sidebar.markdown("Find Me On: ")
st.sidebar.markdown(
    "**Email: [dyanaqlima323@gmail.com](dyanaqlima323@gmail.com)**")
st.sidebar.markdown(
    "**ID Dicoding: [dyanaqlima](https://www.dicoding.com/users/dyanaqlima/academies)**")
st.sidebar.markdown(
    "**LinkedIn: [Dyan Aqlima Febriyanti](https://www.linkedin.com/in/dyan-aqlima-febriyanti/)**")
st.sidebar.markdown(
    "**Github: [dyanaqlima323](https://github.com/dyanaqlima323)**")


