# -*- coding: utf-8 -*-
"""Bike Analysis - Bangkit

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p3a2AXQDAkVmAyFho2oNFSFuCrjyikqq

# Proyek Analisis Data: [Input Nama Dataset]
- **Nama:** Dyan Aqlima Febriyanti
- **Email:** dyanaqlima323@gmail.com
- **ID Dicoding:** Dyan Aqlima Febriyanti

## Menentukan Pertanyaan Bisnis
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
st.set_option('deprecation.showPyplotGlobalUse', False)
sns.set(style='dark')

day_df=pd.read_csv('https://raw.githubusercontent.com/dyanaqlima323/Machine-Learning-Bangkit-H1/8a153b8c0b68ee947840c89c75c4ca6f581c6d21/day.csv')

hour_df=pd.read_csv('https://raw.githubusercontent.com/dyanaqlima323/Machine-Learning-Bangkit-H1/8a153b8c0b68ee947840c89c75c4ca6f581c6d21/hour.csv')

"""## Cleaning Data

### Data Frame Day
"""

#Mengubah nama kolom
day_df.rename(columns={'dteday' : 'date', 'yr': 'year', 'mnth': 'month'}, inplace=True)

#Mengganti tipe data
day_df['date'] = pd.to_datetime(day_df['date'])

day_df.info()

"""### Data Frame Hour"""

#Mengganti tipe data
hour_df['dteday'] = pd.to_datetime(hour_df['dteday'])

#Mengubah nama kolom
hour_df.rename(columns={'dteday' : 'date', 'yr': 'year', 'mnth': 'month', 'hr' : 'hour'}, inplace=True)


"""## Visualization & Explanatory Analysis

### **Pertanyaan 1: Apakah libur (holiday) memiliki pengaruh terhadap pola penggunaan sepeda? Apakah ada peningkatan atau penurunan jumlah pengguna sepeda selama libur?**
"""

# Pisahkan data berdasarkan hari libur dan non-libur
holiday_data = day_df[day_df['holiday'] == 1]
non_holiday_data = day_df[day_df['holiday'] == 0]

# Hitung rata-rata jumlah pengguna sepeda untuk setiap kategori
avg_cnt_holiday = holiday_data['cnt'].mean()
avg_cnt_non_holiday = non_holiday_data['cnt'].mean()

# Tampilkan rata-rata jumlah pengguna sepeda pada hari libur dan non-libur
st.subheader('Average Bike Users on Holiday vs. Non-Holiday')
col1, col2 = st.columns(2)

with col1:
    st.metric("Holiday", value=avg_cnt_holiday)

with col2:
    st.metric("Non-Holiday", value=avg_cnt_non_holiday)

# Visualisasikan perbedaan jumlah pengguna sepeda antara hari libur dan non-libur
plt.figure(figsize=(8, 6))
plt.bar(['Holiday', 'Non-Holiday'], [avg_cnt_holiday, avg_cnt_non_holiday], color=['red', '#28E841'])
plt.title('Average Bike Users on Holiday vs. Non-Holiday')
plt.xlabel('Day Type')
plt.ylabel('Average Bike Users (cnt)')
st.pyplot()


"""### **Pertanyaan 2 : Bagaimana kondisi cuaca memengaruhi jumlah pengguna sepeda?**"""

# Buat strip plot untuk membandingkan jumlah pengguna sepeda berdasarkan kondisi cuaca
st.subheader('Effect of Weather Conditions on Bike Usage')

plt.figure(figsize=(10, 6))
sns.stripplot(x='weathersit', y='cnt', data=day_df, palette='muted', alpha=0.7)
plt.title('Effect of Weather Conditions on Bike Usage')
plt.xlabel('Weather Condition')
plt.ylabel('Bike Users Count')
plt.xticks(ticks=[0, 1, 2], labels=['Clear', 'Mist', 'Light Rain/Heavy Rain'])
plt.grid(True)
st.pyplot()


"""## Conclusion

- Conclution pertanyaan 1. Apakah libur (holiday) memiliki pengaruh terhadap pola penggunaan sepeda? Apakah ada peningkatan atau penurunan jumlah pengguna sepeda selama libur?

 -> Jawab:
Pola penggunaan sepeda cenderung lebih tinggi pada hari non-holiday daripada pada hari libur, mungkin karena orang-orang memilih aktivitas lain saat libur atau karena perbedaan rutinitas harian. Jumlah pengguna sepeda cenderung lebih rendah pada hari libur. Adapun strategi yang mungkin untuk menarik lebih banyak pengguna sepeda pada hari libur, seperti:
   *   Promo khusus dengan penawaran atau diskon liburan
   *   Penyesuaian persediaan sepeda berdasarkan data historis untuk memastikan ketersediaan yang memadai
   *   Mengadakan acara khusus atau tur bersepeda dengan tema liburan untuk meningkatkan minat masyarakat dalam bersepeda.

- Conclution pertanyaan 2. Apakah terdapat tren peningkatan atau penurunan dalam penggunaan sepeda dari musim ke musim dalam beberapa tahun terakhir?

->  Jawab:

 - Conclution pertanyaan 2. Bagaimana kondisi cuaca memengaruhi jumlah pengguna sepeda?

->  Jawab:
Berdasarkan analisis visual pola penggunaan sepeda pada kondisi cuaca yang berbeda, terlihat bahwa jumlah pengguna sepeda cenderung lebih banyak saat cuaca cerah (clear) dan lebih sedikit saat cuaca hujan ringan (light rain). Hal ini menunjukkan bahwa kondisi cuaca memengaruhi pola penggunaan sepeda, dengan cuaca cerah cenderung meningkatkan jumlah penggunaan sepeda dan cuaca hujan ringan cenderung mengurangi jumlah penggunaan sepeda. Oleh karena itu, kondisi cuaca dapat memainkan peran penting dalam pola penggunaan sepeda
"""

# Tampilan Streamlit

with st.sidebar:
    # Menambahkan logo perusahaan
    st.image("https://github.com/dicodingacademy/assets/raw/main/logo.png")